[2024-08-08 09:30:35,690] [DXL_Communication] [ERROR]: activateDXLConnection : 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyserial-3.5-py3.10.egg/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pangolin/pangolin_ws/src/pangolin_robot/pangolin_base/DXL_motor_control.py", line 46, in activateDXLConnection
    if self.port_handler.openPort():
  File "/usr/local/lib/python3.10/dist-packages/dynamixel_sdk-3.7.51-py3.10.egg/dynamixel_sdk/port_handler.py", line 44, in openPort
    return self.setBaudRate(self.baudrate)
  File "/usr/local/lib/python3.10/dist-packages/dynamixel_sdk-3.7.51-py3.10.egg/dynamixel_sdk/port_handler.py", line 68, in setBaudRate
    return self.setupPort(baud)
  File "/usr/local/lib/python3.10/dist-packages/dynamixel_sdk-3.7.51-py3.10.egg/dynamixel_sdk/port_handler.py", line 114, in setupPort
    self.ser = serial.Serial(
  File "/usr/local/lib/python3.10/dist-packages/pyserial-3.5-py3.10.egg/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/usr/local/lib/python3.10/dist-packages/pyserial-3.5-py3.10.egg/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
[2024-08-08 09:30:35,693] [DXL_Communication] [WARNING]: activateDXLConnection : Failed to open the port
[2024-08-08 09:30:35,693] [DXL_Communication] [WARNING]: activateDXLConnection : System will run WITHOUT Real Mortor
